// src/actions/actionTypes.js

const ACTION_TYPES = {
  SET_CONTACTS: 'SET_CONTACTS',
  SET_CONTACT_FOR_EDIT: 'SET_CONTACT_FOR_EDIT',
  ADD_CONTACT: 'ADD_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
};

export default ACTION_TYPES;
